version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:password@db/prompts"
      FOUNDELASTICSEARCH_URL: http://elasticsearch:9200
      OPENAI_KEY: ${OPENAI_KEY}
    stdin_open: true
    tty: true
    volumes:
      - .:/rails:rw
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5444:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    deploy: # it is too greedy
      resources:
        limits:
          memory: 2500M
        reservations:
          memory: 2G
